### ISSUE TITLE
Logsheets are containing values from the BERGEN observatory and not (only) from the ESC86N observatory

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/observatory-esc68n-crate#3]
Hello, 

https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/filtered/water_observatory.csv
The obs_id should be ESC68N and not Bergen. ESC68N is in Tromso (not Bergen). 

There are also issues here
https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/filtered/water_sampling.csv
https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/raw/water_observatory.csv
https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/raw/water_sampling.csv
https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/transformed/water_observatory.csv
https://github.com/emo-bon/observatory-esc68n-crate/blob/main/logsheets/transformed/water_sampling.csv

Should this be corrected in the original Google spreadsheets and then re-harvested here?

**Comment by cpavloud** [comment]
I will create a pull request to correct the files.

**Comment by cpavloud** [comment]
The pull request cannot proceed because of conflicts. So this issue remains open and it is very important.

In the water_sampling.csv files: The station is not **Bergen**, the station is **ESC68N** (located in Tromso)

The water_observatory.csv files should be:
project_name,latitude,longitude,geo_loc_name,loc_broad_ocean,loc_broad_ocean_mrgid,loc_regional,loc_regional_mrgid,loc_loc,loc_loc_mrgid,env_broad_biome,env_local,env_package,tot_depth_water_col,organization,organization_country,organization_edmoid,obs_id,wa_id,extra_site_info,contact_name,contact_email,contact_orcid,ENA_accession_number_umbrella,ENA_accession_number_project
 EMOBON,68.925895,17.125619,Norway,Arctic Ocean,http://marineregions.org/mrgid/1906,Norwegian Sea,http://marineregions.org/mrgid/2353,Norwegian part of the Norwegian Sea,http://marineregions.org/mrgid/25242,marine biome [ENVO:00000447];marine pelagic biome [ENVO:01000023],marine pelagic feature [ENVO:01000044];marine water body [ENVO:00001999];costal water body [ENVO:02000049];fjord [ENVO_00000039],water,,The Arctic University of Norway (UiT),Norway,https://edmo.seadatanet.org/report/5354,ESC68N,ESC68N Wa,,Kim Praebel,Kim.praebel@uit.no,https://orcid.org/0000-0002-0681-1854,https://www.ebi.ac.uk/ena/browser/view/PRJEB51688,https://www.ebi.ac.uk/ena/browser/view/PRJEB51654 


@melinalou can you check it out?

**Comment by melinalou** [comment]
Hi Christina!
Yes I will have a look now and I'll let you know.

All the best,
Melina

**Comment by cpavloud** [comment]
I already did the changes in the log sheet for this one.
If you go to the google spreadsheet, you will see my comments as to what I have changed. 
Not sure what needs to be done after that so that the .csv files are updated too.

**Comment by melinalou** [comment]
When I was correcting the logsheets I only had to correct them in github https://github.com/emo-bon/governance-data/blob/main/logsheets.csv when they sent me a logfile and then submit a comment that I corrected the errors I could correct. Are you referring in something else? As I saw you also did the changes there.

**Comment by cpavloud** [comment]
The changes should made to the actual logsheets (the google spreadsheets) because they are harvested to github. 
@kmexter right?

**Comment by melinalou** [comment]
So, the actual logsheets are not those that can be found here https://github.com/emo-bon/governance-data/blob/main/logsheets.csv right? And I think these are here https://drive.google.com/drive/folders/1kJXi46_8TydJuxb8Ltbd5eLOW1aUKIc3 ?

As I can notice, the changes you made in the ESC68N_UiT are shown in both files(one from the first link, github and the other from the drive folder), in which did you make the changes? I think that if we change something on github files it also changes in the actual drive files cause are the same files linked, but I am not sure at all.

I tested that again and I think the answer in this "Not sure what needs to be done after that so that the .csv files are updated too." is that they are updated automatically.

**Comment by kmexter** [comment]
https://github.com/emo-bon/governance-data/blob/main/logsheets.csv is the file that lists the URLs of the logsheets for the observatories that we currently know about, ie. currently all the Wa and So ones, as well as controlling who should be doing the QC on those and what date ranges the QC should be applied to
Your second link - by the way thanks for that, I didn't know it - are all the Wa observatories, yes

[cid:01c4c0cc-a4a4-4a1e-8fd8-d7c59b6ad398]
________________________________

**Comment by melinalou** [comment]
Good! So the changes should be made on those files https://github.com/emo-bon/governance-data/blob/main/logsheets.csv 
 right?

**Comment by kmexter** [comment]
We need changes to the 3 CSVs called observatory, organisations, and logsheets in https://github.com/emo-bon/governance-data/tree/main so we can add in the ARMS ones

[cid:75c16ea1-ed11-4ff4-81d5-5ac55aabf386]
________________________________

**Comment by melinalou** [comment]
ok! I will follow the issues on github and I will fix what I can.

**Comment by kmexter** [comment]
Wait, I was confused by the emails
Melina - you should only change the googlesheets for Wa and Ha as you do the QC
The only people who should be adding anything to the files in https://github.com/emo-bon/governance-data/tree/main are Christina and me (I don't think Melanthia or Melina have permission)
The googlesheets that need to be checked for QC by Melina are those on https://drive.google.com/drive/folders/1kJXi46_8TydJuxb8Ltbd5eLOW1aUKIc3 and  https://drive.google.com/drive/folders/1nhBmpHIJ60k30shRkKq5p9uyBWGpZouk

Are we clear?

[cid:1d5c9401-d28e-4c79-abbe-28c1741c3d53]
________________________________

**Comment by melinalou** [comment]
Yes I think we are on the same page. I am making the changes to those files https://github.com/emo-bon/governance-data/blob/main/logsheets.csv that are the same with https://drive.google.com/drive/folders/1kJXi46_8TydJuxb8Ltbd5eLOW1aUKIc3 (I mean the changes are updated there). Correct?
I am not making any changes here https://github.com/emo-bon/governance-data/tree/main

No..now I see that is the same link..so I am confused again. Maybe you want me not to change the files in github but only in the drive folder in order to not change the github ones? Sorry for any confusion but it is not really clear to me cause until now I worked [there](https://github.com/emo-bon/governance-data/blob/main/logsheets.csv).

**Comment by kmexter** [comment]
ah, you mean you are looking at the files that are listed IN https://github.com/emo-bon/governance-data/blob/main/logsheets.csv<https://github.com/emo-bon/governance-data/blob/main/logsheets.csv>? IF so, then yes, that is what you should be doing
phew, I had a minor panic there 🙂


[cid:dc4e9e73-e541-43fa-9e7a-46d2bde87bc0]
________________________________

**Comment by melinalou** [comment]
Ouf, me too!
Thank youu!

**Comment by cpavloud** [comment]
If this is completed, then feel free to close it.

**Comment by kmexter** [comment]
I believe this is closed....I am sorry for the confusion between the logsheets on the googledrive and those on GH. As I said in another issue, we are having problems running the harvesting procedure so the files in GH are currently NOT updated as the files in google are. Hoping @marc-portier can fix this in the next few weeks.
